Catch error caused by missing $DISPLAY.
dbus-daemon cannot launch without a $DISPLAY variable set. The program now catches this and gives a softer error message with exit 1

diff --git a/clementeyene b/clementeyene
--- a/clementeyene
+++ b/clementeyene
@@ -5,6 +5,10 @@ case $(dbus-send --session --type=method_call --print-reply --dest=org.mpris.Med
                 echo "dbus service not found. Is Clementine running?"
                 exit 1
                 ;;
+	'Failed to open connection to "session" message bus: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11')
+		echo "dbus-daemon failed to launch because of missing \$DISPLAY. Is Xorg running?"
+		exit 1
+		;;
         *)
                 break
                 ;;
